preload = ~/.local/share/backgrounds/apelsin_dolki_suhoj_1157829_1920x1080.jpg
wallpaper = eDP-1,~/.local/share/backgrounds/apelsin_dolki_suhoj_1157829_1920x1080.jpg
wallpaper = HDMI-A-2,~/.local/share/backgrounds/apelsin_dolki_suhoj_1157829_1920x1080.jpg

