preload = ~/files/wallpaper/zima_sneg_siluet_131193_1920x1080.jpg 
wallpaper = eDP-1,~/files/wallpaper/zima_sneg_siluet_131193_1920x1080.jpg
wallpaper = HDMI-A-2,~/files/wallpaper/zima_sneg_siluet_131193_1920x1080.jpg
