# ouch plugin. Compress 
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

# recycle-bin plugin
[[mgr.prepend_keymap]] # Go to Trash directory
on = [ "g", "t", ]
run = "plugin recycle-bin open"
desc = "Go to Trash"

[[mgr.prepend_keymap]] # Open the trash
on = [ "R", "o", ]
run = "plugin recycle-bin open"
desc = "Open Trash"

[[mgr.prepend_keymap]] # Empty the trash
on = [ "R", "e", ]
run = "plugin recycle-bin empty"
desc = "Empty Trash"

[[mgr.prepend_keymap]] # Delete selected items from trash
on = [ "R", "d", ]
run = "plugin recycle-bin delete"
desc = "Delete from Trash"

[[mgr.prepend_keymap]] # Empty trash by days since deleted
on = [ "R", "D", ]
run = "plugin recycle-bin emptyDays"
desc = "Empty by days deleted"

[[mgr.prepend_keymap]] # Restore selected items from trash
on = [ "R", "r", ]
run = "plugin recycle-bin restore"
desc = "Restore from Trash"

# restore plugin
[[mgr.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders" 

# [[mgr.prepend_keymap]] # or use "d + u" like me
# on = ["d", "u"]
# run = "plugin restore"
# desc = "Restore last deleted files/folders" 
#
# [[mgr.prepend_keymap]] # This will throw error when there is existed file/folder
# on = [ "d", "U" ]
# run = "plugin restore -- --interactive"
# desc = "Restore deleted files/folders (Interactive)"

# [[mgr.prepend_keymap]] # Or auto overwrite existed file/folder
# on = [ "d", "U" ]
# run = "plugin restore -- --interactive --interactive-overwrite"
# desc = "Restore deleted files/folders (Interactive overwrite)" 
  
